# Linear Algebra in Python

<div class="alert alert-block alert-success">
<b>Goals:</b> 

* Demonstrate practical applications of math notions in a series of toy examples.
</div>



<div class="alert alert-block alert-info">
<b>Content:</b> In this notebook, we demonstrate linear combinations of vectors and matrix operations!
</div>

In [1]:
import numpy as np

# Linear combinations

In [2]:
v1=np.array([1,0,0])
v2=np.array([0,1,0])
v3=np.array([0,0,1])

In [3]:
lin_comb = 2*v1 + 3*v2 + 4*v3
lin_comb

array([2, 3, 4])

<div class="alert alert-block alert-success">
<b>Observation:</b> Much in the same way, we can generate every vector in $\mathbb{R}^3$!
</div>


# Matrix Multiplication

In [4]:
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[1,2,3],[4,5,6]])
C=np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
A,B,C

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]))

Which matrix multiplications are possible with two of the above?

In [5]:
np.matmul(A,C)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128]])

In [6]:
np.matmul(B,C)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128]])

In [8]:
#np.matmul(A,B)
#np.matmul(B,A)
#np.matmul(C,A)
#np.matmul(C,B)

In [9]:
Bt=B.transpose()
Bt

array([[1, 4],
       [2, 5],
       [3, 6]])

In [10]:
np.matmul(A,Bt)

array([[14, 32],
       [32, 77]])

<div class="alert alert-block alert-warning">
<b>Warning:</b> Transposing a matrix yields a <b>different</b> matrix!
    
* $A\cdot B^T$ is not the same as $A\cdot B$.
* Transposition must NOT be treated as a means to "make the multiplication possible".
</div>


## Rank and Inverse of a Matrix

In [11]:
import numpy.linalg as la

In [12]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
la.matrix_rank(A)

2

The matrix has full rank.

In [14]:
#la.inv(A)

LinAlgError: Last 2 dimensions of the array must be square

<div class="alert alert-block alert-warning">
<b>Warning:</b> One condition for the invertability of a matrix it that it must at least be square. 
</div>

### A Very Simple Example
Let's use a square matrix with obviously independent rows.

In [15]:
M=np.array([[1,0],[0,1]])
la.matrix_rank(M)

2

In [16]:
la.inv(M)

array([[1., 0.],
       [0., 1.]])

### Another Simple example

In [17]:
M=np.array([[2,0],[0,2]])
la.matrix_rank(M)

2

In [18]:
Mi=np.linalg.inv(M)
Mi

array([[0.5, 0. ],
       [0. , 0.5]])

Verify the properties of the inverse:

In [19]:
np.matmul(M, Mi), np.matmul(Mi,M)

(array([[1., 0.],
        [0., 1.]]),
 array([[1., 0.],
        [0., 1.]]))

### A Less Obvious Example

In [23]:
M=np.array([[2,7],[1,2]])
la.matrix_rank(M)

2

In [24]:
Mi=np.linalg.inv(M)
Mi

array([[-0.66666667,  2.33333333],
       [ 0.33333333, -0.66666667]])

Verify the properties of the inverse:

In [25]:
np.matmul(M, Mi), np.matmul(Mi,M)

(array([[ 1.00000000e+00, -3.33066907e-16],
        [ 0.00000000e+00,  1.00000000e+00]]),
 array([[1., 0.],
        [0., 1.]]))

### A Singular Example

In [26]:
M=np.array([[2,7],[1,3.5]])
la.matrix_rank(M)

1

In [ ]:
#np.linalg.inv(M)

## Checking Linear Independence

In [27]:
a=np.array([1,1,2])
b=np.array([3,7,2])
c=np.array([2,10,-4])

To check for independence, we have to solve the equation system $x\cdot a + y\cdot b + z\cdot c = 0$.

Equivalently, we can ceck whether the matrix with $a,b,c$ as rows has full rank.

In [28]:
M=np.matrix([a,b,c])
la.matrix_rank(M)

2

Thus, the vectors are not linear independent!

Indeed, we can express the zero vector with 

In [29]:
4*a-2*b +c

array([0, 0, 0])

This also means, that we can express at least one of the three vectors as linear combination of the others (in this particular case, it works for all three):

In [30]:
c==2*b-4*a

array([ True,  True,  True])

<div class="alert alert-block alert-info">
<b>Take Aways:</b> 

* Vector and Matrix operations are available through numpy (especially numpy.linalg).
* Computing linear combinations is trivial.
* Checking for linear independence is non-trivial. One way is using the matrix rank function in numpy.
</div>



<div class="alert alert-block alert-success">
<b>Play with:</b> 

* Create another set of vectors, e.g. with higher dimensionality and different numbers and check their linear independence.
* Create deliberately linear dependen vectors.
* Create random matrices and see if they are invertible.
</div>
