Exercise 2
Exercise 2.1
Run the following code

In [4]:
import pandas as pd

grades_df = pd.read_csv('grades.csv', index_col=0)
grades = grades_df.to_numpy()


Display both grades_df and grades. How do they differ?
Using your numpy array grades calculate the following statistics::
• What is the average grade of all students and tasks?
• What is the average grade per student?
• What is the average grade per task?
• What is the median grade per task?

In [5]:
print(grades)
print(grades_df)

# Calculate statistics
average_grade = np.mean(grades)                  # Average grade of all students and tasks
average_grade_per_student = np.mean(grades, axis=1)  # Average grade per student
average_grade_per_task = np.mean(grades, axis=0)     # Average grade per task
median_grade_per_task = np.median(grades, axis=0)    # Median grade per task

# Display the statistics
print("\nStatistics:")
print(f"Average grade of all students and tasks: {average_grade:.2f}")
print(f"Average grade per student: {average_grade_per_student}")
print(f"Average grade per task: {average_grade_per_task}")
print(f"Median grade per task: {median_grade_per_task}")

[[80 60 70]
 [90 80 85]
 [70 50 70]]
       task1  task2  task3
name                      
Anna      80     60     70
Berta     90     80     85
Chris     70     50     70

Statistics:
Average grade of all students and tasks: 72.78
Average grade per student: [70.         85.         63.33333333]
Average grade per task: [80.         63.33333333 75.        ]
Median grade per task: [80. 60. 70.]


: 